ALTER TABLE NOTICIAS DROP FOREIGN KEY FK_NOTICIAS_ONG_ID
ALTER TABLE PROYECTO DROP FOREIGN KEY FK_PROYECTO_ONG_ID
ALTER TABLE ACTIVIDADES DROP FOREIGN KEY FK_ACTIVIDADES_ID_PROYECTO
ALTER TABLE DEMANDA DROP FOREIGN KEY FK_DEMANDA_UNIVERSIDAD_ID_UNIVERSIDAD
ALTER TABLE DEMANDA DROP FOREIGN KEY FK_DEMANDA_PAS_ID
ALTER TABLE DEMANDA DROP FOREIGN KEY FK_DEMANDA_PROYECTO_ID_PROYECTO
ALTER TABLE DEMANDA DROP FOREIGN KEY FK_DEMANDA_PDI_ID
ALTER TABLE DEMANDA DROP FOREIGN KEY FK_DEMANDA_ALUMNO_ID
ALTER TABLE usuario DROP FOREIGN KEY FK_usuario_UNIVERSIDAD_ID_UNIVERSIDAD
ALTER TABLE ALUMNO DROP FOREIGN KEY FK_ALUMNO_ID
ALTER TABLE ONG DROP FOREIGN KEY FK_ONG_ID
ALTER TABLE PAS DROP FOREIGN KEY FK_PAS_ID
ALTER TABLE PDI DROP FOREIGN KEY FK_PDI_ID
ALTER TABLE VOLUNTARIADO DROP FOREIGN KEY FK_VOLUNTARIADO_ID_PROYECTO
ALTER TABLE Alumno_DESTINOS_DESEADOS DROP FOREIGN KEY FK_Alumno_DESTINOS_DESEADOS_Alumno_ID
ALTER TABLE Alumno_IDIOMAS DROP FOREIGN KEY FK_Alumno_IDIOMAS_Alumno_ID
ALTER TABLE Alumno_SOLICITUDES DROP FOREIGN KEY FK_Alumno_SOLICITUDES_Alumno_ID
ALTER TABLE ONG_NOTICIAS DROP FOREIGN KEY FK_ONG_NOTICIAS_ONG_ID
ALTER TABLE ONG_PROYECTO DROP FOREIGN KEY FK_ONG_PROYECTO_ONG_ID
ALTER TABLE PAS_SOLICITUDES DROP FOREIGN KEY FK_PAS_SOLICITUDES_PAS_ID
ALTER TABLE PDI_SOLICITUDES DROP FOREIGN KEY FK_PDI_SOLICITUDES_PDI_ID
ALTER TABLE Proyecto_PARTICIPANTES DROP FOREIGN KEY FK_Proyecto_PARTICIPANTES_Proyecto_ID_PROYECTO
ALTER TABLE Universidad_FACULTADES DROP FOREIGN KEY Universidad_FACULTADES_Universidad_ID_UNIVERSIDAD
ALTER TABLE Universidad_SOLICITUDES DROP FOREIGN KEY Universidad_SOLICITUDES_Universidad_ID_UNIVERSIDAD
ALTER TABLE Universidad_USUARIOS DROP FOREIGN KEY FK_Universidad_USUARIOS_Universidad_ID_UNIVERSIDAD
DROP TABLE NOTICIAS
DROP TABLE PROYECTO
DROP TABLE ACTIVIDADES
DROP TABLE DEMANDA
DROP TABLE usuario
DROP TABLE ALUMNO
DROP TABLE ONG
DROP TABLE PAS
DROP TABLE PDI
DROP TABLE UNIVERSIDAD
DROP TABLE VOLUNTARIADO
DROP TABLE Alumno_DESTINOS_DESEADOS
DROP TABLE Alumno_IDIOMAS
DROP TABLE Alumno_SOLICITUDES
DROP TABLE ONG_NOTICIAS
DROP TABLE ONG_PROYECTO
DROP TABLE PAS_SOLICITUDES
DROP TABLE PDI_SOLICITUDES
DROP TABLE Proyecto_PARTICIPANTES
DROP TABLE Universidad_FACULTADES
DROP TABLE Universidad_SOLICITUDES
DROP TABLE Universidad_USUARIOS
DELETE FROM SEQUENCE WHERE SEQ_NAME = 'SEQ_GEN'
